import json
from pathlib import Path


def load_text(path):
    return Path(path).read_text()


def load_plan():
    plan_path = Path("plan.json")
    assert plan_path.exists(), "plan.json was not generated by the harness"
    return json.loads(plan_path.read_text())


def planned_resources(plan):
    resources = {}
    for change in plan.get("resource_changes", []):
        after = change.get("change", {}).get("after")
        if after is not None:
            resources[change["address"]] = {
                "type": change["type"],
                "name": change["name"],
                "values": after,
            }
    return resources


def resource_values(resources, address):
    assert address in resources, f"resource {address} missing from plan"
    return resources[address]["values"]


def planned_outputs(plan):
    return plan.get("planned_values", {}).get("outputs", {})


def count_addresses(resources, prefix):
    return sum(1 for address in resources if address.startswith(prefix))


def test_source_uses_single_main_tf_file_and_provider_inputs():
    main_tf = load_text("main.tf")
    terraform_files = sorted(path.name for path in Path(".").glob("*.tf"))

    assert terraform_files == ["main.tf"]
    assert 'provider "aws"' in main_tf
    assert 'variable "aws_region"' in main_tf
    assert 'variable "aws_endpoint"' in main_tf
    assert 'variable "aws_access_key_id"' in main_tf
    assert 'variable "aws_secret_access_key"' in main_tf
    assert 'default     = "us-east-1"' in main_tf
    assert 'region                      = var.aws_region' in main_tf
    assert 'endpoints {' in main_tf
    assert 's3             = var.aws_endpoint' in main_tf
    assert 'sts            = var.aws_endpoint' in main_tf
    assert 'name_prefix' not in main_tf
    assert 'variable "bucket_name"' not in main_tf


def test_plan_contains_core_resources():
    resources = planned_resources(load_plan())

    expected_addresses = {
        "aws_vpc.main",
        "aws_lambda_function.backend",
        "aws_db_instance.relational_backbone",
        "aws_s3_bucket.raw_events",
        "aws_s3_bucket_versioning.raw_events",
        "aws_s3_bucket_server_side_encryption_configuration.raw_events",
        "aws_s3_bucket_lifecycle_configuration.raw_events",
        "aws_sqs_queue.event_queue",
        "aws_dynamodb_table.idempotency",
        "aws_api_gateway_rest_api.ingest_api",
        "aws_api_gateway_resource.ingest_resource",
        "aws_api_gateway_method.ingest_post",
        "aws_api_gateway_stage.prod",
        "aws_lambda_permission.api_gateway",
        "aws_sfn_state_machine.orchestration",
        "aws_cloudwatch_event_rule.scheduled_execution",
        "aws_sns_topic.operational_notifications",
    }

    missing = expected_addresses - resources.keys()
    assert not missing, f"missing planned resources: {sorted(missing)}"


def test_plan_has_exact_counts_for_key_resources():
    resources = planned_resources(load_plan())

    assert "aws_iam_role.backend_execution_role" in resources
    assert "aws_iam_role.state_machine_role" in resources
    assert count_addresses(resources, "aws_kms_key.") == 1
    assert count_addresses(resources, "aws_kms_alias.") == 1
    assert count_addresses(resources, "aws_secretsmanager_secret.") == 1
    assert count_addresses(resources, "aws_secretsmanager_secret_version.") == 1
    assert count_addresses(resources, "aws_iam_policy.") == 2
    assert count_addresses(resources, "aws_subnet.private_") == 2
    assert count_addresses(resources, "aws_subnet.public_") == 2
    assert count_addresses(resources, "aws_internet_gateway.") == 1
    assert count_addresses(resources, "aws_route_table.public") == 1
    assert count_addresses(resources, "aws_route_table.private") == 1
    assert count_addresses(resources, "aws_nat_gateway.") == 1
    assert count_addresses(resources, "aws_eip.") == 1
    assert count_addresses(resources, "aws_vpc_endpoint.") == 1
    assert count_addresses(resources, "aws_cloudwatch_log_group.") == 2
    assert count_addresses(resources, "aws_sns_topic.") == 1
    assert count_addresses(resources, "aws_security_group.") == 2
    assert count_addresses(resources, "aws_route_table_association.public_") == 2
    assert count_addresses(resources, "aws_route_table_association.private_") == 2


def test_plan_configures_kms_secrets_and_database_credentials_flow():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")

    kms_key = resource_values(resources, "aws_kms_key.data_at_rest")
    kms_alias = resource_values(resources, "aws_kms_alias.data_at_rest_alias")
    secret = resource_values(resources, "aws_secretsmanager_secret.db_credentials")
    secret_version = resource_values(resources, "aws_secretsmanager_secret_version.db_credentials_version")
    db = resource_values(resources, "aws_db_instance.relational_backbone")

    assert kms_key["enable_key_rotation"] is True
    assert kms_alias["name"] == "alias/data-at-rest"
    assert secret["name"] == "db-credentials"
    assert secret["recovery_window_in_days"] == 0
    assert "username" in secret_version["secret_string"]
    assert "password" in secret_version["secret_string"]
    assert db["engine"] == "postgres"
    assert db["engine_version"] == "15"
    assert db["instance_class"] == "db.t3.micro"
    assert db["allocated_storage"] == 20
    assert db["storage_type"] == "gp2"
    assert db["storage_encrypted"] is True
    assert db["backup_retention_period"] == 7
    assert "jsondecode(aws_secretsmanager_secret_version.db_credentials_version.secret_string).username" in main_tf
    assert "jsondecode(aws_secretsmanager_secret_version.db_credentials_version.secret_string).password" in main_tf


def test_plan_configures_network_topology_and_security_rules():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")

    vpc = resource_values(resources, "aws_vpc.main")
    private_subnet_1 = resource_values(resources, "aws_subnet.private_1")
    private_subnet_2 = resource_values(resources, "aws_subnet.private_2")
    public_subnet_1 = resource_values(resources, "aws_subnet.public_1")
    public_subnet_2 = resource_values(resources, "aws_subnet.public_2")
    nat_gateway = resource_values(resources, "aws_nat_gateway.nat")
    eip = resource_values(resources, "aws_eip.nat")
    endpoint = resource_values(resources, "aws_vpc_endpoint.s3_gateway")
    db_ingress = resource_values(resources, "aws_security_group_rule.db_ingress")
    db_egress = resource_values(resources, "aws_security_group_rule.db_egress")
    execution_egress = resource_values(resources, "aws_security_group_rule.execution_env_egress")

    assert vpc["cidr_block"] == "10.0.0.0/16"
    assert private_subnet_1["cidr_block"] == "10.0.1.0/24"
    assert private_subnet_2["cidr_block"] == "10.0.2.0/24"
    assert public_subnet_1["cidr_block"] == "10.0.101.0/24"
    assert public_subnet_2["cidr_block"] == "10.0.102.0/24"
    assert public_subnet_1["map_public_ip_on_launch"] is True
    assert public_subnet_2["map_public_ip_on_launch"] is True
    assert eip["domain"] == "vpc"
    assert "subnet_id" not in nat_gateway or nat_gateway["subnet_id"] is not None
    assert endpoint["vpc_endpoint_type"] == "Gateway"
    assert db_ingress["from_port"] == 5432
    assert db_ingress["to_port"] == 5432
    assert db_egress["protocol"] == "-1"
    assert execution_egress["protocol"] == "-1"
    assert 'resource "aws_internet_gateway" "gw"' in main_tf
    assert 'resource "aws_route_table" "public"' in main_tf
    assert 'resource "aws_route_table" "private"' in main_tf
    assert 'destination_cidr_block = "0.0.0.0/0"' in main_tf
    assert 'cidr_blocks       = [aws_vpc.main.cidr_block]' in main_tf
    assert 'source_security_group_id = aws_security_group.execution_env.id' in main_tf
    assert 'prefix_list_ids   = [aws_vpc_endpoint.s3_gateway.prefix_list_id]' in main_tf
    assert 'resource "aws_vpc_endpoint_policy" "s3_gateway_policy"' in main_tf
    assert '"s3:*"' in main_tf


def test_plan_configures_storage_queue_and_table_requirements():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")

    bucket_versioning = resource_values(resources, "aws_s3_bucket_versioning.raw_events")
    bucket_encryption = resource_values(resources, "aws_s3_bucket_server_side_encryption_configuration.raw_events")
    bucket_lifecycle = resource_values(resources, "aws_s3_bucket_lifecycle_configuration.raw_events")
    queue = resource_values(resources, "aws_sqs_queue.event_queue")
    table = resource_values(resources, "aws_dynamodb_table.idempotency")

    assert bucket_versioning["versioning_configuration"][0]["status"] == "Enabled"
    assert bucket_encryption["rule"][0]["apply_server_side_encryption_by_default"][0]["sse_algorithm"] == "aws:kms"
    lifecycle_rules = {rule["id"]: rule for rule in bucket_lifecycle["rule"]}
    assert lifecycle_rules["expire-old-versions"]["noncurrent_version_expiration"][0]["noncurrent_days"] == 30
    assert lifecycle_rules["abort-incomplete-multipart"]["abort_incomplete_multipart_upload"][0]["days_after_initiation"] == 7
    assert lifecycle_rules["expire-current-objects"]["expiration"][0]["days"] == 365
    assert queue["message_retention_seconds"] == 1209600
    assert queue["visibility_timeout_seconds"] == 60
    assert queue.get("kms_master_key_id") is not None or "kms_master_key_id" in main_tf
    assert table["billing_mode"] == "PAY_PER_REQUEST"
    assert table["hash_key"] == "pk"
    assert table["ttl"][0]["attribute_name"] == "expiresAt"


def test_plan_configures_iam_alarm_logs_and_sns():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")

    backend_role = resource_values(resources, "aws_iam_role.backend_execution_role")
    state_role = resource_values(resources, "aws_iam_role.state_machine_role")
    backend_attachment = resource_values(resources, "aws_iam_role_policy_attachment.backend_policy_attachment")
    state_attachment = resource_values(resources, "aws_iam_role_policy_attachment.state_machine_policy_attachment")
    lambda_alarm = resource_values(resources, "aws_cloudwatch_metric_alarm.lambda_errors")
    backend_log_group = resource_values(resources, "aws_cloudwatch_log_group.backend")
    state_log_group = resource_values(resources, "aws_cloudwatch_log_group.state_machine")
    sns_topic = resource_values(resources, "aws_sns_topic.operational_notifications")

    assert "lambda.amazonaws.com" in backend_role["assume_role_policy"]
    assert "states.amazonaws.com" in state_role["assume_role_policy"]
    assert backend_attachment["role"] == "backend-execution-role"
    assert state_attachment["role"] == "state-machine-role"
    assert sns_topic.get("name") is not None or sns_topic.get("arn") is not None
    assert lambda_alarm["metric_name"] == "Errors"
    assert lambda_alarm["threshold"] == 1
    assert lambda_alarm["dimensions"]["FunctionName"]
    assert backend_log_group["retention_in_days"] == 14
    assert state_log_group["retention_in_days"] == 14
    assert "logs:CreateLogGroup" in main_tf
    assert "s3:GetObject" in main_tf
    assert "s3:PutObject" in main_tf
    assert "s3:ListBucket" in main_tf
    assert "sqs:SendMessage" in main_tf
    assert "sqs:GetQueueAttributes" in main_tf
    assert "kms:GenerateDataKey" in main_tf
    assert "lambda:InvokeFunction" in main_tf
    assert "logs:PutLogEvents" in main_tf
    assert "logs:GetLogDelivery" in main_tf
    assert "logs:DescribeLogGroups" in main_tf
    assert "logs:CreateLogDelivery" in main_tf
    assert 'Service = "cloudwatch.amazonaws.com"' in main_tf
    assert lambda_alarm["period"] == 300


def test_plan_limits_wildcard_resource_usage_to_expected_cases():
    main_tf = load_text("main.tf")

    wildcard_lines = [
        line.strip()
        for line in main_tf.splitlines()
        if 'Resource = "*"' in line or 'Resource  = "*"' in line
    ]

    assert wildcard_lines
    assert len(wildcard_lines) <= 8
    assert '"kms:*"' in main_tf
    assert '"xray:PutTraceSegments"' in main_tf
    assert '"xray:PutTelemetryRecords"' in main_tf


def test_plan_scopes_backend_and_state_machine_policy_resources():
    main_tf = load_text("main.tf")

    assert 'arn:aws:logs:${var.aws_region}:${local.account_id}:log-group:/aws/lambda/*' in main_tf
    assert '"arn:aws:s3:::${aws_s3_bucket.raw_events.id}"' in main_tf
    assert '"arn:aws:s3:::${aws_s3_bucket.raw_events.id}/*"' in main_tf
    assert "Resource = aws_sqs_queue.event_queue.arn" in main_tf
    assert "Resource = aws_kms_key.data_at_rest.arn" in main_tf
    assert "Resource = aws_lambda_function.backend.arn" in main_tf
    assert "Resource = aws_cloudwatch_log_group.state_machine.arn" in main_tf


def test_plan_configures_lambda_api_workflow_and_xray_behavior():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    lambda_source = load_text("lambda/index.js")

    lambda_fn = resource_values(resources, "aws_lambda_function.backend")
    api_resource = resource_values(resources, "aws_api_gateway_resource.ingest_resource")
    api_method = resource_values(resources, "aws_api_gateway_method.ingest_post")

    assert lambda_fn["runtime"] == "nodejs20.x"
    assert lambda_fn["handler"] == "index.handler"
    assert lambda_fn["memory_size"] == 256
    assert lambda_fn["timeout"] == 10
    assert lambda_fn["reserved_concurrent_executions"] == 5
    assert len(lambda_fn["vpc_config"]) == 1
    assert lambda_fn["vpc_config"][0].get("subnet_ids") is None or len(lambda_fn["vpc_config"][0]["subnet_ids"]) == 2
    assert lambda_fn["vpc_config"][0].get("security_group_ids") is None or len(lambda_fn["vpc_config"][0]["security_group_ids"]) == 1
    assert api_resource["path_part"] == "ingest"
    assert api_method["http_method"] == "POST"
    assert api_method["authorization"] == "NONE"
    assert 'data "archive_file" "lambda_package"' in main_tf
    assert 'source_dir  = "${path.module}/lambda"' in main_tf
    assert 'type                    = "AWS_PROXY"' in main_tf
    assert 'integration_http_method = "POST"' in main_tf
    assert 'tracing_config {' in main_tf
    assert 'mode = "Active"' in main_tf
    assert 'resource "aws_xray_group" "lambda_tracing"' in main_tf
    assert 'count = local.is_local_mode ? 0 : 1' in main_tf
    assert "if (action === 'enqueue')" in lambda_source
    assert "if (action === 'archive')" in lambda_source
    assert "sqs.sendMessage" in lambda_source
    assert "s3.putObject" in lambda_source
    assert "dynamodb.putItem" in lambda_source
    assert "ConditionExpression: 'attribute_not_exists(pk)'" in lambda_source


def test_plan_configures_api_gateway_permission_scope_and_eventbridge_input():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    permission = resource_values(resources, "aws_lambda_permission.api_gateway")
    event_target = resource_values(resources, "aws_cloudwatch_event_target.state_machine_target")

    assert permission["principal"] == "apigateway.amazonaws.com"
    assert "POST/ingest" in main_tf
    assert event_target["target_id"] == "state-machine-target"
    assert 'requestId = "scheduled"' in main_tf


def test_plan_configures_step_functions_workflow_and_outputs():
    resources = planned_resources(load_plan())
    outputs = planned_outputs(load_plan())
    main_tf = load_text("main.tf")
    state_machine = resource_values(resources, "aws_sfn_state_machine.orchestration")

    assert state_machine["name"] == "orchestration"
    assert "EnqueueEvents" in main_tf
    assert "ArchiveEvents" in main_tf
    assert 'action = "enqueue"' in main_tf
    assert 'action = "archive"' in main_tf
    assert set(outputs) == {
        "api_invoke_url",
        "s3_bucket_name",
        "sqs_queue_url",
        "rds_endpoint",
    }


def test_requirement_single_terraform_hcl_file_named_main_tf():
    assert sorted(path.name for path in Path(".").glob("*.tf")) == ["main.tf"]


def test_requirement_provider_uses_aws_region_default_us_east_1():
    main_tf = load_text("main.tf")
    assert 'variable "aws_region"' in main_tf
    assert 'default     = "us-east-1"' in main_tf
    assert 'region                      = var.aws_region' in main_tf


def test_requirement_provider_uses_aws_endpoint_service_base():
    main_tf = load_text("main.tf")
    assert 'variable "aws_endpoint"' in main_tf
    assert 'endpoints {' in main_tf
    assert 's3             = var.aws_endpoint' in main_tf
    assert 'sts            = var.aws_endpoint' in main_tf


def test_requirement_exactly_one_kms_alias_targeting_created_key():
    resources = planned_resources(load_plan())
    alias_values = resource_values(resources, "aws_kms_alias.data_at_rest_alias")
    assert count_addresses(resources, "aws_kms_alias.") == 1
    assert alias_values["name"] == "alias/data-at-rest"


def test_requirement_exactly_one_secret_and_one_secret_version_with_json_credentials():
    resources = planned_resources(load_plan())
    secret = resource_values(resources, "aws_secretsmanager_secret.db_credentials")
    secret_version = resource_values(resources, "aws_secretsmanager_secret_version.db_credentials_version")
    assert count_addresses(resources, "aws_secretsmanager_secret.") == 1
    assert count_addresses(resources, "aws_secretsmanager_secret_version.") == 1
    assert secret["name"] == "db-credentials"
    assert "username" in secret_version["secret_string"]
    assert "password" in secret_version["secret_string"]


def test_requirement_database_reads_credentials_from_secrets_manager():
    main_tf = load_text("main.tf")
    assert "jsondecode(aws_secretsmanager_secret_version.db_credentials_version.secret_string).username" in main_tf
    assert "jsondecode(aws_secretsmanager_secret_version.db_credentials_version.secret_string).password" in main_tf


def test_requirement_backend_policy_scopes_logs_s3_sqs_and_kms_resources():
    main_tf = load_text("main.tf")
    assert 'arn:aws:logs:${var.aws_region}:${local.account_id}:log-group:/aws/lambda/*' in main_tf
    assert '"arn:aws:s3:::${aws_s3_bucket.raw_events.id}"' in main_tf
    assert '"arn:aws:s3:::${aws_s3_bucket.raw_events.id}/*"' in main_tf
    assert "Resource = aws_sqs_queue.event_queue.arn" in main_tf
    assert "Resource = aws_kms_key.data_at_rest.arn" in main_tf


def test_requirement_state_machine_policy_scopes_lambda_sqs_and_logs_resources():
    main_tf = load_text("main.tf")
    assert "lambda:InvokeFunction" in main_tf
    assert "sqs:SendMessage" in main_tf
    assert "logs:CreateLogDelivery" in main_tf
    assert "Resource = aws_lambda_function.backend.arn" in main_tf
    assert "Resource = aws_sqs_queue.event_queue.arn" in main_tf
    assert "Resource = aws_cloudwatch_log_group.state_machine.arn" in main_tf


def test_requirement_no_wildcard_resource_except_required_cases():
    main_tf = load_text("main.tf")
    wildcard_lines = [
        line.strip()
        for line in main_tf.splitlines()
        if 'Resource = "*"' in line or 'Resource  = "*"' in line
    ]
    assert wildcard_lines
    assert len(wildcard_lines) <= 8


def test_requirement_public_and_private_subnets_use_different_availability_zones():
    resources = planned_resources(load_plan())
    private_1 = resource_values(resources, "aws_subnet.private_1")
    private_2 = resource_values(resources, "aws_subnet.private_2")
    public_1 = resource_values(resources, "aws_subnet.public_1")
    public_2 = resource_values(resources, "aws_subnet.public_2")
    assert private_1["availability_zone"] != private_2["availability_zone"]
    assert public_1["availability_zone"] != public_2["availability_zone"]


def test_requirement_internet_gateway_route_tables_and_associations_exist():
    resources = planned_resources(load_plan())
    assert count_addresses(resources, "aws_internet_gateway.") == 1
    assert count_addresses(resources, "aws_route_table.public") == 1
    assert count_addresses(resources, "aws_route_table.private") == 1
    assert count_addresses(resources, "aws_route_table_association.public_") == 2
    assert count_addresses(resources, "aws_route_table_association.private_") == 2


def test_requirement_two_security_groups_exist_with_expected_boundary_rules():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    assert count_addresses(resources, "aws_security_group.") == 2
    assert 'source_security_group_id = aws_security_group.execution_env.id' in main_tf
    assert 'cidr_blocks       = [aws_vpc.main.cidr_block]' in main_tf
    assert 'prefix_list_ids   = [aws_vpc_endpoint.s3_gateway.prefix_list_id]' in main_tf


def test_requirement_s3_endpoint_attaches_to_both_route_tables_and_bucket_policy():
    main_tf = load_text("main.tf")
    assert 'route_table_ids = [' in main_tf
    assert 'aws_route_table.public.id' in main_tf
    assert 'aws_route_table.private.id' in main_tf
    assert 'resource "aws_vpc_endpoint_policy" "s3_gateway_policy"' in main_tf
    assert '"arn:aws:s3:::${aws_s3_bucket.raw_events.id}"' in main_tf


def test_requirement_rds_specific_configuration_flags():
    resources = planned_resources(load_plan())
    db = resource_values(resources, "aws_db_instance.relational_backbone")
    assert db["allocated_storage"] == 20
    assert db["storage_type"] == "gp2"
    assert db["multi_az"] is False
    assert db["publicly_accessible"] is False
    assert db["deletion_protection"] is False
    assert db["auto_minor_version_upgrade"] is True


def test_requirement_dynamodb_pitr_sse_and_ttl_are_enabled():
    resources = planned_resources(load_plan())
    table = resource_values(resources, "aws_dynamodb_table.idempotency")
    assert table["point_in_time_recovery"][0]["enabled"] is True
    assert table["server_side_encryption"][0]["enabled"] is True
    assert table["ttl"][0]["attribute_name"] == "expiresAt"


def test_requirement_exactly_two_log_groups_are_encrypted_and_retained_14_days():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    backend = resource_values(resources, "aws_cloudwatch_log_group.backend")
    state = resource_values(resources, "aws_cloudwatch_log_group.state_machine")
    assert count_addresses(resources, "aws_cloudwatch_log_group.") == 2
    assert backend["retention_in_days"] == 14
    assert state["retention_in_days"] == 14
    assert backend.get("kms_key_id") is not None or "kms_key_id" in main_tf
    assert state.get("kms_key_id") is not None or "kms_key_id" in main_tf


def test_requirement_lambda_inline_archive_vpc_and_behavior_details():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    lambda_source = load_text("lambda/index.js")
    lambda_fn = resource_values(resources, "aws_lambda_function.backend")
    assert 'data "archive_file" "lambda_package"' in main_tf
    assert len(lambda_fn["vpc_config"]) == 1
    assert lambda_fn["vpc_config"][0].get("subnet_ids") is None or len(lambda_fn["vpc_config"][0]["subnet_ids"]) == 2
    assert lambda_fn["vpc_config"][0].get("security_group_ids") is None or len(lambda_fn["vpc_config"][0]["security_group_ids"]) == 1
    assert "sqs.sendMessage" in lambda_source
    assert "s3.putObject" in lambda_source
    assert "pk: { S: requestId }" in lambda_source
    assert "Math.floor(Date.now() / 1000) + 86400" in lambda_source
    assert "ConditionalCheckFailedException" in lambda_source


def test_requirement_api_gateway_ingest_post_and_lambda_permission_scope():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    api_resource = resource_values(resources, "aws_api_gateway_resource.ingest_resource")
    api_method = resource_values(resources, "aws_api_gateway_method.ingest_post")
    permission = resource_values(resources, "aws_lambda_permission.api_gateway")
    assert api_resource["path_part"] == "ingest"
    assert api_method["http_method"] == "POST"
    assert api_method["authorization"] == "NONE"
    assert permission["principal"] == "apigateway.amazonaws.com"
    assert "POST/ingest" in main_tf


def test_requirement_step_functions_eventbridge_and_alarm_to_sns():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    alarm = resource_values(resources, "aws_cloudwatch_metric_alarm.lambda_errors")
    event_target = resource_values(resources, "aws_cloudwatch_event_target.state_machine_target")
    assert 'requestId = "scheduled"' in main_tf
    assert event_target["target_id"] == "state-machine-target"
    assert "EnqueueEvents" in main_tf
    assert "ArchiveEvents" in main_tf
    assert 'level                  = "ALL"' in main_tf
    assert alarm["threshold"] == 1
    assert alarm["period"] == 300
    assert alarm.get("alarm_actions") is not None or "alarm_actions" in main_tf


def test_requirement_xray_group_tracing_and_minimal_permissions_exist():
    main_tf = load_text("main.tf")
    assert 'resource "aws_xray_group" "lambda_tracing"' in main_tf
    assert 'filter_expression = "service(Lambda)"' in main_tf
    assert 'tracing_config {' in main_tf
    assert 'mode = "Active"' in main_tf
    assert '"xray:PutTraceSegments"' in main_tf
    assert '"xray:PutTelemetryRecords"' in main_tf


def test_requirement_single_terraform_hcl_file_named_main_tf_explicit():
    assert Path("main.tf").exists()
    assert sorted(path.name for path in Path(".").glob("*.tf")) == ["main.tf"]


def test_requirement_aws_provider_with_aws_region_default_us_east_1_explicit():
    main_tf = load_text("main.tf")
    assert 'provider "aws"' in main_tf
    assert 'variable "aws_region"' in main_tf
    assert 'default     = "us-east-1"' in main_tf
    assert 'region                      = var.aws_region' in main_tf


def test_requirement_aws_provider_with_aws_endpoint_configuration_explicit():
    main_tf = load_text("main.tf")
    assert 'variable "aws_endpoint"' in main_tf
    assert 'endpoints {' in main_tf
    assert 's3             = var.aws_endpoint' in main_tf
    assert 'sts            = var.aws_endpoint' in main_tf


def test_requirement_exactly_one_kms_alias_explicit():
    resources = planned_resources(load_plan())
    alias_values = resource_values(resources, "aws_kms_alias.data_at_rest_alias")
    assert count_addresses(resources, "aws_kms_alias.") == 1
    assert alias_values["name"] == "alias/data-at-rest"


def test_requirement_exactly_one_secrets_manager_secret_explicit():
    resources = planned_resources(load_plan())
    secret = resource_values(resources, "aws_secretsmanager_secret.db_credentials")
    assert count_addresses(resources, "aws_secretsmanager_secret.") == 1
    assert secret["name"] == "db-credentials"


def test_requirement_exactly_one_secret_version_with_username_password_json_explicit():
    resources = planned_resources(load_plan())
    secret_version = resource_values(resources, "aws_secretsmanager_secret_version.db_credentials_version")
    assert count_addresses(resources, "aws_secretsmanager_secret_version.") == 1
    assert "username" in secret_version["secret_string"]
    assert "password" in secret_version["secret_string"]


def test_requirement_database_reads_credentials_from_secrets_manager_explicit():
    main_tf = load_text("main.tf")
    assert "jsondecode(aws_secretsmanager_secret_version.db_credentials_version.secret_string).username" in main_tf
    assert "jsondecode(aws_secretsmanager_secret_version.db_credentials_version.secret_string).password" in main_tf


def test_requirement_exactly_two_public_subnets_correct_cidrs_explicit():
    resources = planned_resources(load_plan())
    public_1 = resource_values(resources, "aws_subnet.public_1")
    public_2 = resource_values(resources, "aws_subnet.public_2")
    assert public_1["cidr_block"] == "10.0.101.0/24"
    assert public_2["cidr_block"] == "10.0.102.0/24"


def test_requirement_different_availability_zones_for_subnets_explicit():
    resources = planned_resources(load_plan())
    private_1 = resource_values(resources, "aws_subnet.private_1")
    private_2 = resource_values(resources, "aws_subnet.private_2")
    public_1 = resource_values(resources, "aws_subnet.public_1")
    public_2 = resource_values(resources, "aws_subnet.public_2")
    assert private_1["availability_zone"] != private_2["availability_zone"]
    assert public_1["availability_zone"] != public_2["availability_zone"]


def test_requirement_exactly_one_internet_gateway_explicit():
    resources = planned_resources(load_plan())
    assert count_addresses(resources, "aws_internet_gateway.") == 1


def test_requirement_exactly_one_public_route_table_with_default_route_explicit():
    resources = planned_resources(load_plan())
    route = resource_values(resources, "aws_route.public_internet")
    assert count_addresses(resources, "aws_route_table.public") == 1
    assert route["destination_cidr_block"] == "0.0.0.0/0"


def test_requirement_exactly_one_private_route_table_with_nat_route_explicit():
    resources = planned_resources(load_plan())
    route = resource_values(resources, "aws_route.private_nat")
    assert count_addresses(resources, "aws_route_table.private") == 1
    assert route["destination_cidr_block"] == "0.0.0.0/0"


def test_requirement_exactly_two_security_groups_explicit():
    resources = planned_resources(load_plan())
    assert count_addresses(resources, "aws_security_group.") == 2


def test_requirement_lambda_inline_archive_strategy_explicit():
    main_tf = load_text("main.tf")
    assert 'data "archive_file" "lambda_package"' in main_tf
    assert 'source_dir  = "${path.module}/lambda"' in main_tf


def test_requirement_lambda_deterministic_behaviors_enqueue_archive_explicit():
    lambda_source = load_text("lambda/index.js")
    assert "if (action === 'enqueue')" in lambda_source
    assert "sqs.sendMessage" in lambda_source
    assert "if (action === 'archive')" in lambda_source
    assert "s3.putObject" in lambda_source


def test_requirement_dynamodb_conditional_write_logic_explicit():
    lambda_source = load_text("lambda/index.js")
    assert "dynamodb.putItem" in lambda_source
    assert "ConditionExpression: 'attribute_not_exists(pk)'" in lambda_source
    assert "ConditionalCheckFailedException" in lambda_source


def test_requirement_sns_topic_policy_explicit():
    main_tf = load_text("main.tf")
    assert 'resource "aws_sns_topic_policy" "operational_notifications_policy"' in main_tf
    assert 'Service = "cloudwatch.amazonaws.com"' in main_tf


def test_requirement_xray_group_and_lambda_tracing_explicit():
    main_tf = load_text("main.tf")
    assert 'resource "aws_xray_group" "lambda_tracing"' in main_tf
    assert 'filter_expression = "service(Lambda)"' in main_tf
    assert 'tracing_config {' in main_tf
    assert 'mode = "Active"' in main_tf


def test_requirement_minimal_xray_permissions_explicit():
    main_tf = load_text("main.tf")
    assert '"xray:PutTraceSegments"' in main_tf
    assert '"xray:PutTelemetryRecords"' in main_tf


def test_requirement_four_specific_outputs_explicit():
    outputs = planned_outputs(load_plan())
    assert set(outputs) == {
        "api_invoke_url",
        "s3_bucket_name",
        "sqs_queue_url",
        "rds_endpoint",
    }


def test_requirement_sns_topic_policy_for_cloudwatch_only_explicit():
    main_tf = load_text("main.tf")
    assert 'resource "aws_sns_topic_policy" "operational_notifications_policy"' in main_tf
    assert 'Service = "cloudwatch.amazonaws.com"' in main_tf
    assert 'Action   = "sns:Publish"' in main_tf


def test_requirement_xray_tracing_group_for_lambda_explicit():
    main_tf = load_text("main.tf")
    assert 'resource "aws_xray_group" "lambda_tracing"' in main_tf
    assert 'group_name        = "lambda-tracing"' in main_tf
    assert 'filter_expression = "service(Lambda)"' in main_tf


def test_requirement_lambda_active_tracing_enabled_explicit():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    lambda_fn = resource_values(resources, "aws_lambda_function.backend")
    assert 'tracing_config {' in main_tf
    assert 'mode = "Active"' in main_tf
    assert lambda_fn["tracing_config"][0]["mode"] == "Active"


def test_requirement_lambda_role_xray_permissions_explicit():
    main_tf = load_text("main.tf")
    assert '"xray:PutTraceSegments"' in main_tf
    assert '"xray:PutTelemetryRecords"' in main_tf
    assert 'resource "aws_iam_policy" "backend_policy"' in main_tf


def test_requirement_only_specified_inputs_exist_explicit():
    main_tf = load_text("main.tf")
    assert 'variable "aws_region"' in main_tf
    assert 'variable "aws_endpoint"' in main_tf
    assert 'variable "aws_access_key_id"' in main_tf
    assert 'variable "aws_secret_access_key"' in main_tf
    assert 'variable "name_prefix"' not in main_tf
    assert 'variable "bucket_name"' not in main_tf


def test_requirement_no_external_variables_or_hard_coded_names_explicit():
    main_tf = load_text("main.tf")
    assert 'name_prefix' not in main_tf
    assert 'variable "bucket_name"' not in main_tf
    assert 'var.name_' not in main_tf
    assert 'variable "name_prefix"' not in main_tf
    assert 'variable "bucket_name"' not in main_tf


def test_requirement_deterministic_resource_naming_explicit():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    bucket = resource_values(resources, "aws_s3_bucket.raw_events")
    assert 'resource "random_id" "bucket_prefix"' in main_tf
    assert 'bucket = "raw-events-${random_id.bucket_prefix.hex}"' in main_tf
    assert bucket.get("bucket") is None or "${random_id.bucket_prefix.hex}" in bucket["bucket"] or bucket["bucket"]


def test_requirement_four_specific_outputs_api_bucket_queue_rds_explicit():
    outputs = planned_outputs(load_plan())
    assert "api_invoke_url" in outputs
    assert "s3_bucket_name" in outputs
    assert "sqs_queue_url" in outputs
    assert "rds_endpoint" in outputs


def test_requirement_single_terraform_hcl_file_named_main_tf_redundant_explicit():
    assert Path("main.tf").exists()
    assert len(list(Path(".").glob("*.tf"))) == 1


def test_requirement_aws_provider_with_aws_region_default_us_east_1_redundant_explicit():
    main_tf = load_text("main.tf")
    assert 'provider "aws"' in main_tf
    assert 'default     = "us-east-1"' in main_tf
    assert 'region                      = var.aws_region' in main_tf


def test_requirement_aws_provider_with_aws_endpoint_configuration_redundant_explicit():
    main_tf = load_text("main.tf")
    assert 'variable "aws_endpoint"' in main_tf
    assert 'endpoints {' in main_tf
    assert 'apigateway     = var.aws_endpoint' in main_tf
    assert 'lambda         = var.aws_endpoint' in main_tf


def test_traceability_single_terraform_hcl_file_named_main_tf():
    """Single Terraform HCL file named main.tf."""
    assert Path("main.tf").exists()
    assert sorted(path.name for path in Path(".").glob("*.tf")) == ["main.tf"]


def test_traceability_aws_provider_with_aws_region_default_us_east_1():
    """AWS provider with AWS_REGION default us-east-1."""
    main_tf = load_text("main.tf")
    assert 'variable "aws_region"' in main_tf
    assert 'default     = "us-east-1"' in main_tf
    assert 'region                      = var.aws_region' in main_tf


def test_traceability_aws_provider_with_aws_endpoint_as_service_endpoint():
    """AWS provider with AWS_ENDPOINT as service endpoint."""
    main_tf = load_text("main.tf")
    assert 'variable "aws_endpoint"' in main_tf
    assert 'endpoints {' in main_tf
    assert 's3             = var.aws_endpoint' in main_tf
    assert 'sts            = var.aws_endpoint' in main_tf


def test_traceability_exactly_one_kms_alias():
    """Exactly 1 KMS alias."""
    resources = planned_resources(load_plan())
    assert count_addresses(resources, "aws_kms_alias.") == 1
    assert resource_values(resources, "aws_kms_alias.data_at_rest_alias")["name"] == "alias/data-at-rest"


def test_traceability_exactly_one_secrets_manager_secret_for_db_credentials():
    """Exactly 1 Secrets Manager secret for DB credentials."""
    resources = planned_resources(load_plan())
    assert count_addresses(resources, "aws_secretsmanager_secret.") == 1
    assert resource_values(resources, "aws_secretsmanager_secret.db_credentials")["name"] == "db-credentials"


def test_traceability_exactly_one_secret_version_with_json_username_password():
    """Exactly 1 secret version with JSON username/password."""
    resources = planned_resources(load_plan())
    secret_version = resource_values(resources, "aws_secretsmanager_secret_version.db_credentials_version")
    assert count_addresses(resources, "aws_secretsmanager_secret_version.") == 1
    assert "username" in secret_version["secret_string"]
    assert "password" in secret_version["secret_string"]


def test_traceability_database_reads_credentials_from_secrets_manager():
    """Database reads credentials from Secrets Manager."""
    main_tf = load_text("main.tf")
    assert "jsondecode(aws_secretsmanager_secret_version.db_credentials_version.secret_string).username" in main_tf
    assert "jsondecode(aws_secretsmanager_secret_version.db_credentials_version.secret_string).password" in main_tf


def test_traceability_no_wildcard_resource_except_for_logging():
    """No wildcard Resource except for logging."""
    main_tf = load_text("main.tf")
    wildcard_lines = [
        line.strip()
        for line in main_tf.splitlines()
        if 'Resource = "*"' in line or 'Resource  = "*"' in line
    ]
    assert wildcard_lines
    assert len(wildcard_lines) <= 8


def test_traceability_exactly_two_public_subnets_10_0_101_and_10_0_102():
    """Exactly 2 public subnets (10.0.101.0/24, 10.0.102.0/24)."""
    resources = planned_resources(load_plan())
    assert resource_values(resources, "aws_subnet.public_1")["cidr_block"] == "10.0.101.0/24"
    assert resource_values(resources, "aws_subnet.public_2")["cidr_block"] == "10.0.102.0/24"


def test_traceability_two_different_availability_zones():
    """Two different availability zones."""
    resources = planned_resources(load_plan())
    assert resource_values(resources, "aws_subnet.public_1")["availability_zone"] != resource_values(resources, "aws_subnet.public_2")["availability_zone"]
    assert resource_values(resources, "aws_subnet.private_1")["availability_zone"] != resource_values(resources, "aws_subnet.private_2")["availability_zone"]


def test_traceability_exactly_one_internet_gateway():
    """Exactly 1 internet gateway."""
    resources = planned_resources(load_plan())
    assert count_addresses(resources, "aws_internet_gateway.") == 1


def test_traceability_exactly_one_public_route_table_with_default_route():
    """Exactly 1 public route table with default route."""
    resources = planned_resources(load_plan())
    assert count_addresses(resources, "aws_route_table.public") == 1
    assert resource_values(resources, "aws_route.public_internet")["destination_cidr_block"] == "0.0.0.0/0"


def test_traceability_exactly_one_private_route_table():
    """Exactly 1 private route table."""
    resources = planned_resources(load_plan())
    assert count_addresses(resources, "aws_route_table.private") == 1
    assert resource_values(resources, "aws_route.private_nat")["destination_cidr_block"] == "0.0.0.0/0"


def test_traceability_exactly_two_security_groups():
    """Exactly 2 security groups."""
    resources = planned_resources(load_plan())
    assert count_addresses(resources, "aws_security_group.") == 2


def test_traceability_lambda_inline_archive_strategy():
    """Lambda inline archive strategy."""
    main_tf = load_text("main.tf")
    assert 'data "archive_file" "lambda_package"' in main_tf
    assert 'source_dir  = "${path.module}/lambda"' in main_tf


def test_traceability_lambda_behaviors_for_enqueue_and_archive_actions():
    """Lambda behaviors for "enqueue" and "archive" actions."""
    lambda_source = load_text("lambda/index.js")
    assert "if (action === 'enqueue')" in lambda_source
    assert "sqs.sendMessage" in lambda_source
    assert "if (action === 'archive')" in lambda_source
    assert "s3.putObject" in lambda_source


def test_traceability_lambda_dynamodb_conditional_write_logic():
    """Lambda DynamoDB conditional write logic."""
    lambda_source = load_text("lambda/index.js")
    assert "dynamodb.putItem" in lambda_source
    assert "ConditionExpression: 'attribute_not_exists(pk)'" in lambda_source


def test_traceability_step_functions_state_machine_with_two_step_workflow_and_all_logging():
    """Step Functions state machine with two-step workflow. Step Functions execution logging at ALL level."""
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    assert resource_values(resources, "aws_sfn_state_machine.orchestration")["name"] == "orchestration"
    assert "EnqueueEvents" in main_tf
    assert "ArchiveEvents" in main_tf
    assert 'level                  = "ALL"' in main_tf


def test_traceability_sns_topic_for_notifications_and_cloudwatch_policy():
    """SNS topic for notifications. SNS topic policy for CloudWatch only."""
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    assert resource_values(resources, "aws_sns_topic.operational_notifications").get("name") is not None or resource_values(resources, "aws_sns_topic.operational_notifications").get("arn") is not None
    assert 'resource "aws_sns_topic_policy" "operational_notifications_policy"' in main_tf
    assert 'Service = "cloudwatch.amazonaws.com"' in main_tf
    assert 'Action   = "sns:Publish"' in main_tf


def test_traceability_xray_group_lambda_active_tracing_and_minimal_permissions():
    """X-Ray group for Lambda service. Lambda active tracing enabled. Lambda role with minimal X-Ray permissions."""
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    assert 'resource "aws_xray_group" "lambda_tracing"' in main_tf
    assert 'filter_expression = "service(Lambda)"' in main_tf
    assert resource_values(resources, "aws_lambda_function.backend")["tracing_config"][0]["mode"] == "Active"
    assert '"xray:PutTraceSegments"' in main_tf
    assert '"xray:PutTelemetryRecords"' in main_tf


def test_traceability_four_specific_outputs_api_url_bucket_queue_rds():
    """4 specific outputs (API URL, bucket name, queue URL, RDS endpoint)."""
    outputs = planned_outputs(load_plan())
    assert set(outputs) == {
        "api_invoke_url",
        "s3_bucket_name",
        "sqs_queue_url",
        "rds_endpoint",
    }


def test_traceability_exactly_two_iam_policies_with_specific_permissions():
    """Exactly 2 IAM policies with specific permissions."""
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    assert count_addresses(resources, "aws_iam_policy.") == 2
    assert 'resource "aws_iam_policy" "backend_policy"' in main_tf
    assert 'resource "aws_iam_policy" "state_machine_policy"' in main_tf
    assert '"logs:CreateLogGroup"' in main_tf
    assert '"logs:CreateLogStream"' in main_tf
    assert '"logs:PutLogEvents"' in main_tf
    assert '"s3:GetObject"' in main_tf
    assert '"s3:PutObject"' in main_tf
    assert '"s3:ListBucket"' in main_tf
    assert '"sqs:SendMessage"' in main_tf
    assert '"sqs:GetQueueAttributes"' in main_tf
    assert '"kms:Encrypt"' in main_tf
    assert '"kms:Decrypt"' in main_tf
    assert '"kms:GenerateDataKey"' in main_tf
    assert '"lambda:InvokeFunction"' in main_tf
    assert '"logs:CreateLogDelivery"' in main_tf


def test_requirement_sns_topic_policy_for_cloudwatch_only():
    main_tf = load_text("main.tf")
    assert 'resource "aws_sns_topic_policy" "operational_notifications_policy"' in main_tf
    assert 'Service = "cloudwatch.amazonaws.com"' in main_tf
    assert 'Action   = "sns:Publish"' in main_tf
    assert "aws_sns_topic.operational_notifications.arn" in main_tf


def test_requirement_xray_tracing_group_for_lambda():
    main_tf = load_text("main.tf")
    assert 'resource "aws_xray_group" "lambda_tracing"' in main_tf
    assert 'group_name        = "lambda-tracing"' in main_tf
    assert 'filter_expression = "service(Lambda)"' in main_tf


def test_requirement_lambda_active_tracing_enabled():
    resources = planned_resources(load_plan())
    lambda_fn = resource_values(resources, "aws_lambda_function.backend")
    assert lambda_fn["tracing_config"][0]["mode"] == "Active"


def test_requirement_lambda_role_xray_permissions():
    main_tf = load_text("main.tf")
    assert '"xray:PutTraceSegments"' in main_tf
    assert '"xray:PutTelemetryRecords"' in main_tf
    assert 'resource "aws_iam_policy" "backend_policy"' in main_tf


def test_requirement_only_specified_inputs_aws_endpoint_region_access_key_secret_key():
    main_tf = load_text("main.tf")
    variable_names = {
        line.split('"')[1]
        for line in main_tf.splitlines()
        if line.strip().startswith('variable "')
    }
    assert variable_names == {
        "aws_region",
        "aws_endpoint",
        "aws_access_key_id",
        "aws_secret_access_key",
    }


def test_requirement_no_external_variables_or_hard_coded_naming_inputs():
    main_tf = load_text("main.tf")
    assert 'variable "name_prefix"' not in main_tf
    assert 'variable "bucket_name"' not in main_tf
    assert 'variable "project_name"' not in main_tf
    assert "var.name_prefix" not in main_tf
    assert "var.bucket_name" not in main_tf
    assert "var.project_name" not in main_tf


def test_requirement_deterministic_resource_naming():
    resources = planned_resources(load_plan())
    main_tf = load_text("main.tf")
    bucket = resource_values(resources, "aws_s3_bucket.raw_events")
    assert 'resource "random_id" "bucket_prefix"' in main_tf
    assert 'bucket = "raw-events-${random_id.bucket_prefix.hex}"' in main_tf
    assert bucket.get("bucket") is None or bucket["bucket"]


def test_requirement_four_specific_outputs():
    outputs = planned_outputs(load_plan())
    assert set(outputs) == {
        "api_invoke_url",
        "s3_bucket_name",
        "sqs_queue_url",
        "rds_endpoint",
    }


def test_requirement_single_terraform_hcl_file_named_main_tf_again():
    assert Path("main.tf").exists()
    assert sorted(path.name for path in Path(".").glob("*.tf")) == ["main.tf"]


def test_requirement_aws_provider_with_aws_region_default_us_east_1_again():
    main_tf = load_text("main.tf")
    assert 'provider "aws"' in main_tf
    assert 'variable "aws_region"' in main_tf
    assert 'default     = "us-east-1"' in main_tf
    assert 'region                      = var.aws_region' in main_tf


def test_requirement_aws_provider_with_aws_endpoint_configuration_again():
    main_tf = load_text("main.tf")
    assert 'provider "aws"' in main_tf
    assert 'variable "aws_endpoint"' in main_tf
    assert 'endpoints {' in main_tf
    assert 's3             = var.aws_endpoint' in main_tf
    assert 'sts            = var.aws_endpoint' in main_tf
