import json
from pathlib import Path


def load_text(path):
    return Path(path).read_text()


def load_state():
    state_path = Path("state.json")
    assert state_path.exists(), "state.json was not generated by the harness"
    return json.loads(state_path.read_text())


def state_resources(state):
    resources = {}
    root_module = state.get("values", {}).get("root_module", {})
    for resource in root_module.get("resources", []):
        resources[resource["address"]] = resource
    return resources


def resource_values(resources, address):
    assert address in resources, f"resource {address} missing from state"
    return resources[address]["values"]


def state_outputs(state):
    return state.get("values", {}).get("outputs", {})


def count_addresses(resources, prefix):
    return sum(1 for address in resources if address.startswith(prefix))


def test_state_contains_deployed_resources():
    resources = state_resources(load_state())

    expected_addresses = {
        "aws_vpc.main",
        "aws_subnet.private_1",
        "aws_subnet.private_2",
        "aws_subnet.public_1",
        "aws_subnet.public_2",
        "aws_lambda_function.backend",
        "aws_s3_bucket.raw_events",
        "aws_s3_bucket_versioning.raw_events",
        "aws_sqs_queue.event_queue",
        "aws_dynamodb_table.idempotency",
        "aws_api_gateway_stage.prod",
        "aws_sfn_state_machine.orchestration",
    }

    missing = expected_addresses - resources.keys()
    assert not missing, f"missing deployed resources: {sorted(missing)}"


def test_state_has_expected_deployed_resource_counts():
    resources = state_resources(load_state())

    assert count_addresses(resources, "aws_kms_key.") == 1
    assert count_addresses(resources, "aws_kms_alias.") == 1
    assert count_addresses(resources, "aws_secretsmanager_secret.") == 1
    assert count_addresses(resources, "aws_secretsmanager_secret_version.") == 1
    assert count_addresses(resources, "aws_subnet.private_") == 2
    assert count_addresses(resources, "aws_subnet.public_") == 2
    assert count_addresses(resources, "aws_internet_gateway.") == 1
    assert count_addresses(resources, "aws_route_table.public") == 1
    assert count_addresses(resources, "aws_route_table.private") == 1
    assert count_addresses(resources, "aws_route.public_internet") == 1
    assert count_addresses(resources, "aws_route.private_nat") == 1
    assert count_addresses(resources, "aws_route_table_association.public_") == 2
    assert count_addresses(resources, "aws_route_table_association.private_") == 2
    assert count_addresses(resources, "aws_nat_gateway.") == 1
    assert count_addresses(resources, "aws_eip.") == 1
    assert count_addresses(resources, "aws_sns_topic.") == 1
    assert count_addresses(resources, "aws_security_group.") == 2


def test_state_has_expected_runtime_configuration():
    resources = state_resources(load_state())

    lambda_fn = resource_values(resources, "aws_lambda_function.backend")
    queue = resource_values(resources, "aws_sqs_queue.event_queue")
    table = resource_values(resources, "aws_dynamodb_table.idempotency")
    bucket_versioning = resource_values(resources, "aws_s3_bucket_versioning.raw_events")

    assert lambda_fn["function_name"]
    assert lambda_fn["runtime"] == "nodejs20.x"
    assert lambda_fn["memory_size"] == 256
    assert lambda_fn["timeout"] == 10
    assert lambda_fn["reserved_concurrent_executions"] == 5
    assert queue["name"]
    assert queue["kms_master_key_id"]
    assert table["name"]
    assert bucket_versioning["versioning_configuration"][0]["status"] == "Enabled"


def test_state_has_expected_eventing_and_api_wiring():
    resources = state_resources(load_state())

    rule = resource_values(resources, "aws_cloudwatch_event_rule.scheduled_execution")
    target = resource_values(resources, "aws_cloudwatch_event_target.state_machine_target")
    api_stage = resource_values(resources, "aws_api_gateway_stage.prod")
    permission = resource_values(resources, "aws_lambda_permission.api_gateway")

    assert rule["schedule_expression"] == "rate(5 minutes)"
    assert target["target_id"] == "state-machine-target"
    assert json.loads(target["input"]) == {"requestId": "scheduled"}
    assert api_stage["stage_name"] == "prod"
    assert permission["principal"] == "apigateway.amazonaws.com"
    assert "POST/ingest" in permission["source_arn"]


def test_state_has_expected_network_and_database_topology():
    resources = state_resources(load_state())

    vpc = resource_values(resources, "aws_vpc.main")
    public_subnet = resource_values(resources, "aws_subnet.public_1")
    public_subnet_2 = resource_values(resources, "aws_subnet.public_2")
    private_subnet = resource_values(resources, "aws_subnet.private_1")
    private_subnet_2 = resource_values(resources, "aws_subnet.private_2")
    internet_gateway = resource_values(resources, "aws_internet_gateway.gw")
    public_route_table = resource_values(resources, "aws_route_table.public")
    private_route_table = resource_values(resources, "aws_route_table.private")
    public_assoc_1 = resource_values(resources, "aws_route_table_association.public_1")
    public_assoc_2 = resource_values(resources, "aws_route_table_association.public_2")
    private_assoc_1 = resource_values(resources, "aws_route_table_association.private_1")
    private_assoc_2 = resource_values(resources, "aws_route_table_association.private_2")
    nat_gateway = resource_values(resources, "aws_nat_gateway.nat")
    public_route = resource_values(resources, "aws_route.public_internet")
    private_route = resource_values(resources, "aws_route.private_nat")
    db_subnet_group = resource_values(resources, "aws_db_subnet_group.main")
    db = resource_values(resources, "aws_db_instance.relational_backbone")

    assert vpc["cidr_block"] == "10.0.0.0/16"
    assert public_subnet["map_public_ip_on_launch"] is True
    assert public_subnet_2["cidr_block"] == "10.0.102.0/24"
    assert private_subnet["cidr_block"] == "10.0.1.0/24"
    assert private_subnet_2["cidr_block"] == "10.0.2.0/24"
    assert public_subnet["availability_zone"] != public_subnet_2["availability_zone"]
    assert private_subnet["availability_zone"] != private_subnet_2["availability_zone"]
    assert internet_gateway["vpc_id"] == vpc["id"]
    assert public_assoc_1["route_table_id"] == public_route_table["id"]
    assert public_assoc_2["route_table_id"] == public_route_table["id"]
    assert private_assoc_1["route_table_id"] == private_route_table["id"]
    assert private_assoc_2["route_table_id"] == private_route_table["id"]
    assert nat_gateway["subnet_id"] == public_subnet["id"]
    assert public_route["destination_cidr_block"] == "0.0.0.0/0"
    assert private_route["destination_cidr_block"] == "0.0.0.0/0"
    assert public_route["gateway_id"] == internet_gateway["id"]
    assert private_route["nat_gateway_id"] == nat_gateway["id"]
    assert len(db_subnet_group["subnet_ids"]) == 2
    assert db["engine"] == "postgres"
    assert db["storage_encrypted"] is True
    assert db["allocated_storage"] == 20
    assert db["storage_type"] == "gp2"
    assert db["multi_az"] is False
    assert db["publicly_accessible"] is False
    assert db["deletion_protection"] is False
    assert db["backup_retention_period"] == 7
    assert db["auto_minor_version_upgrade"] is True
    assert db["db_subnet_group_name"] == db_subnet_group["name"]


def test_state_has_expected_security_and_encryption_settings():
    resources = state_resources(load_state())

    kms_key = resource_values(resources, "aws_kms_key.data_at_rest")
    bucket_encryption = resource_values(resources, "aws_s3_bucket_server_side_encryption_configuration.raw_events")
    backend_log_group = resource_values(resources, "aws_cloudwatch_log_group.backend")
    state_log_group = resource_values(resources, "aws_cloudwatch_log_group.state_machine")
    queue = resource_values(resources, "aws_sqs_queue.event_queue")
    table = resource_values(resources, "aws_dynamodb_table.idempotency")
    lambda_alarm = resource_values(resources, "aws_cloudwatch_metric_alarm.lambda_errors")
    execution_sg = resource_values(resources, "aws_security_group.execution_env")
    db_sg = resource_values(resources, "aws_security_group.relational_backbone")
    db_egress = resource_values(resources, "aws_security_group_rule.db_egress")
    execution_egress = resource_values(resources, "aws_security_group_rule.execution_env_egress")
    endpoint = resource_values(resources, "aws_vpc_endpoint.s3_gateway")
    endpoint_policy = resource_values(resources, "aws_vpc_endpoint_policy.s3_gateway_policy")
    db = resource_values(resources, "aws_db_instance.relational_backbone")

    assert kms_key["enable_key_rotation"] is True
    assert bucket_encryption["rule"][0]["apply_server_side_encryption_by_default"][0]["sse_algorithm"] == "aws:kms"
    assert bucket_encryption["rule"][0]["apply_server_side_encryption_by_default"][0]["kms_master_key_id"]
    assert backend_log_group["retention_in_days"] == 14
    assert state_log_group["retention_in_days"] == 14
    assert backend_log_group["kms_key_id"]
    assert state_log_group["kms_key_id"]
    assert queue["visibility_timeout_seconds"] == 60
    assert queue["kms_master_key_id"]
    assert table["billing_mode"] == "PAY_PER_REQUEST"
    assert table["point_in_time_recovery"][0]["enabled"] is True
    assert table["server_side_encryption"][0]["enabled"] is True
    assert table["server_side_encryption"][0]["kms_key_arn"]
    assert table["ttl"][0]["attribute_name"] == "expiresAt"
    assert execution_sg.get("ingress", []) == []
    assert db_sg.get("ingress", []) == []
    assert db_egress["cidr_blocks"] == ["10.0.0.0/16"]
    assert execution_egress["prefix_list_ids"]
    assert len(endpoint["route_table_ids"]) == 2
    assert endpoint_policy["policy"]
    assert lambda_alarm["alarm_name"] == "lambda-errors"
    assert lambda_alarm["alarm_actions"]
    assert lambda_alarm["comparison_operator"] == "GreaterThanOrEqualToThreshold"
    assert lambda_alarm["threshold"] == 1
    assert lambda_alarm["period"] == 300
    assert db["kms_key_id"]


def test_state_has_expected_iam_and_lambda_wiring():
    resources = state_resources(load_state())

    lambda_fn = resource_values(resources, "aws_lambda_function.backend")
    backend_role = resource_values(resources, "aws_iam_role.backend_execution_role")
    permission = resource_values(resources, "aws_lambda_permission.api_gateway")
    api_integration = resource_values(resources, "aws_api_gateway_integration.ingest_integration")
    api_resource = resource_values(resources, "aws_api_gateway_resource.ingest_resource")
    api_method = resource_values(resources, "aws_api_gateway_method.ingest_post")
    state_machine = resource_values(resources, "aws_sfn_state_machine.orchestration")
    sns_topic = resource_values(resources, "aws_sns_topic.operational_notifications")
    eventbridge_role = resource_values(resources, "aws_iam_role.eventbridge_role")
    state_machine_policy = resource_values(resources, "aws_iam_policy.state_machine_policy")
    sns_topic_policy = resource_values(resources, "aws_sns_topic_policy.operational_notifications_policy")

    assert backend_role["arn"]
    assert eventbridge_role["arn"]
    assert permission["principal"] == "apigateway.amazonaws.com"
    assert api_resource["path_part"] == "ingest"
    assert api_method["http_method"] == "POST"
    assert api_integration["type"] == "AWS_PROXY"
    assert api_integration["integration_http_method"] == "POST"
    assert len(lambda_fn["vpc_config"][0]["subnet_ids"]) == 2
    assert len(lambda_fn["vpc_config"][0]["security_group_ids"]) == 1
    assert lambda_fn["tracing_config"][0]["mode"] == "Active"
    assert lambda_fn["environment"][0]["variables"]["QUEUE_URL"]
    assert lambda_fn["environment"][0]["variables"]["BUCKET_NAME"]
    assert lambda_fn["environment"][0]["variables"]["TABLE_NAME"]
    assert state_machine["name"] == "orchestration"
    assert "EnqueueEvents" in state_machine["definition"]
    assert "ArchiveEvents" in state_machine["definition"]
    assert '"enqueue"' in state_machine["definition"]
    assert '"archive"' in state_machine["definition"]
    assert state_machine["logging_configuration"][0]["level"] == "ALL"
    assert state_machine["logging_configuration"][0]["include_execution_data"] is True
    assert "lambda:InvokeFunction" in state_machine_policy["policy"]
    assert "sqs:SendMessage" in state_machine_policy["policy"]
    assert "cloudwatch.amazonaws.com" in sns_topic_policy["policy"]
    assert sns_topic["arn"]


def test_state_has_expected_secrets_aliases_and_subnets():
    resources = state_resources(load_state())

    kms_alias = resource_values(resources, "aws_kms_alias.data_at_rest_alias")
    secret = resource_values(resources, "aws_secretsmanager_secret.db_credentials")
    secret_version = resource_values(resources, "aws_secretsmanager_secret_version.db_credentials_version")
    private_subnet_2 = resource_values(resources, "aws_subnet.private_2")
    public_subnet_2 = resource_values(resources, "aws_subnet.public_2")

    assert kms_alias["name"] == "alias/data-at-rest"
    assert secret["name"] == "db-credentials"
    assert "username" in secret_version["secret_string"]
    assert "password" in secret_version["secret_string"]
    assert private_subnet_2["cidr_block"] == "10.0.2.0/24"
    assert public_subnet_2["cidr_block"] == "10.0.102.0/24"


def test_state_has_expected_outputs_and_source_strategy():
    state = load_state()
    outputs = state_outputs(state)
    lambda_source = load_text("lambda/index.js")
    main_tf = load_text("main.tf")

    assert set(outputs) == {
        "api_invoke_url",
        "s3_bucket_name",
        "sqs_queue_url",
        "rds_endpoint",
    }
    assert outputs["s3_bucket_name"]["value"]
    assert "execute-api" in outputs["api_invoke_url"]["value"] or outputs["api_invoke_url"]["value"].endswith("/prod")
    assert outputs["sqs_queue_url"]["value"]
    assert outputs["rds_endpoint"]["value"]
    assert 'data "archive_file" "lambda_package"' in main_tf
    assert 'provider "aws"' in main_tf
    assert 'variable "aws_region"' in main_tf
    assert 'variable "aws_endpoint"' in main_tf
    assert 'variable "aws_access_key_id"' in main_tf
    assert 'variable "aws_secret_access_key"' in main_tf
    assert 'resource "aws_xray_group" "lambda_tracing"' in main_tf
    assert 'filter_expression = "service(Lambda)"' in main_tf
    assert "if (action === 'enqueue')" in lambda_source
    assert "if (action === 'archive')" in lambda_source
    assert "timestamp" in lambda_source
    assert "requestId" in lambda_source
    assert 'Key: `events/${requestId}.json`' in lambda_source
    assert "pk: { S: requestId }" in lambda_source
    assert "Math.floor(Date.now() / 1000) + 86400" in lambda_source
    assert "ConditionExpression: 'attribute_not_exists(pk)'" in lambda_source


def test_requirement_sns_topic_policy_for_cloudwatch_only_integration():
    resources = state_resources(load_state())
    topic_policy = resource_values(resources, "aws_sns_topic_policy.operational_notifications_policy")
    assert "cloudwatch.amazonaws.com" in topic_policy["policy"]
    assert "sns:Publish" in topic_policy["policy"]


def test_requirement_xray_tracing_group_for_lambda_integration():
    main_tf = load_text("main.tf")
    assert 'resource "aws_xray_group" "lambda_tracing"' in main_tf
    assert 'filter_expression = "service(Lambda)"' in main_tf


def test_requirement_lambda_active_tracing_enabled_integration():
    resources = state_resources(load_state())
    lambda_fn = resource_values(resources, "aws_lambda_function.backend")
    assert lambda_fn["tracing_config"][0]["mode"] == "Active"


def test_requirement_lambda_role_xray_permissions_integration():
    main_tf = load_text("main.tf")
    assert '"xray:PutTraceSegments"' in main_tf
    assert '"xray:PutTelemetryRecords"' in main_tf


def test_requirement_only_specified_inputs_aws_endpoint_region_access_key_secret_key_integration():
    main_tf = load_text("main.tf")
    variable_names = {
        line.split('"')[1]
        for line in main_tf.splitlines()
        if line.strip().startswith('variable "')
    }
    assert variable_names == {
        "aws_region",
        "aws_endpoint",
        "aws_access_key_id",
        "aws_secret_access_key",
    }


def test_requirement_no_external_variables_or_hard_coded_names_integration():
    main_tf = load_text("main.tf")
    assert 'variable "name_prefix"' not in main_tf
    assert 'variable "bucket_name"' not in main_tf
    assert 'variable "project_name"' not in main_tf
    assert "var.name_prefix" not in main_tf
    assert "var.bucket_name" not in main_tf
    assert "var.project_name" not in main_tf


def test_requirement_deterministic_resource_naming_integration():
    resources = state_resources(load_state())
    main_tf = load_text("main.tf")
    bucket = resource_values(resources, "aws_s3_bucket.raw_events")
    assert 'resource "random_id" "bucket_prefix"' in main_tf
    assert 'bucket = "raw-events-${random_id.bucket_prefix.hex}"' in main_tf
    assert bucket["bucket"]


def test_requirement_four_specific_outputs_integration():
    outputs = state_outputs(load_state())
    assert set(outputs) == {
        "api_invoke_url",
        "s3_bucket_name",
        "sqs_queue_url",
        "rds_endpoint",
    }


def test_requirement_single_terraform_hcl_file_named_main_tf_integration():
    assert Path("main.tf").exists()
    assert sorted(path.name for path in Path(".").glob("*.tf")) == ["main.tf"]


def test_requirement_aws_provider_with_aws_region_default_us_east_1_integration():
    main_tf = load_text("main.tf")
    assert 'provider "aws"' in main_tf
    assert 'variable "aws_region"' in main_tf
    assert 'default     = "us-east-1"' in main_tf
    assert 'region                      = var.aws_region' in main_tf


def test_requirement_aws_provider_with_aws_endpoint_configuration_integration():
    main_tf = load_text("main.tf")
    assert 'provider "aws"' in main_tf
    assert 'variable "aws_endpoint"' in main_tf
    assert 'endpoints {' in main_tf
    assert 's3             = var.aws_endpoint' in main_tf
    assert 'sts            = var.aws_endpoint' in main_tf


def test_traceability_single_terraform_hcl_file_named_main_tf_integration():
    """Single Terraform HCL file named main.tf."""
    assert Path("main.tf").exists()
    assert sorted(path.name for path in Path(".").glob("*.tf")) == ["main.tf"]


def test_traceability_aws_provider_with_aws_region_default_us_east_1_integration():
    """AWS provider with AWS_REGION default us-east-1."""
    main_tf = load_text("main.tf")
    assert 'variable "aws_region"' in main_tf
    assert 'default     = "us-east-1"' in main_tf
    assert 'region                      = var.aws_region' in main_tf


def test_traceability_aws_provider_with_aws_endpoint_as_service_endpoint_integration():
    """AWS provider with AWS_ENDPOINT as service endpoint."""
    main_tf = load_text("main.tf")
    assert 'variable "aws_endpoint"' in main_tf
    assert 'endpoints {' in main_tf
    assert 's3             = var.aws_endpoint' in main_tf
    assert 'sts            = var.aws_endpoint' in main_tf


def test_traceability_exactly_one_kms_alias_integration():
    """Exactly 1 KMS alias."""
    resources = state_resources(load_state())
    assert count_addresses(resources, "aws_kms_alias.") == 1
    assert resource_values(resources, "aws_kms_alias.data_at_rest_alias")["name"] == "alias/data-at-rest"


def test_traceability_exactly_one_secrets_manager_secret_for_db_credentials_integration():
    """Exactly 1 Secrets Manager secret for DB credentials."""
    resources = state_resources(load_state())
    assert count_addresses(resources, "aws_secretsmanager_secret.") == 1
    assert resource_values(resources, "aws_secretsmanager_secret.db_credentials")["name"] == "db-credentials"


def test_traceability_exactly_one_secret_version_with_json_username_password_integration():
    """Exactly 1 secret version with JSON username/password."""
    resources = state_resources(load_state())
    secret_version = resource_values(resources, "aws_secretsmanager_secret_version.db_credentials_version")
    assert count_addresses(resources, "aws_secretsmanager_secret_version.") == 1
    assert "username" in secret_version["secret_string"]
    assert "password" in secret_version["secret_string"]


def test_traceability_database_reads_credentials_from_secrets_manager_integration():
    """Database reads credentials from Secrets Manager."""
    main_tf = load_text("main.tf")
    assert "jsondecode(aws_secretsmanager_secret_version.db_credentials_version.secret_string).username" in main_tf
    assert "jsondecode(aws_secretsmanager_secret_version.db_credentials_version.secret_string).password" in main_tf


def test_traceability_sns_topic_policy_for_cloudwatch_only_integration():
    """SNS topic policy for CloudWatch only."""
    resources = state_resources(load_state())
    topic_policy = resource_values(resources, "aws_sns_topic_policy.operational_notifications_policy")
    assert "cloudwatch.amazonaws.com" in topic_policy["policy"]
    assert "sns:Publish" in topic_policy["policy"]


def test_traceability_xray_group_for_lambda_service_integration():
    """X-Ray group for Lambda service."""
    main_tf = load_text("main.tf")
    assert 'resource "aws_xray_group" "lambda_tracing"' in main_tf
    assert 'filter_expression = "service(Lambda)"' in main_tf


def test_traceability_lambda_active_tracing_enabled_integration():
    """Lambda active tracing enabled."""
    resources = state_resources(load_state())
    assert resource_values(resources, "aws_lambda_function.backend")["tracing_config"][0]["mode"] == "Active"


def test_traceability_lambda_role_with_minimal_xray_permissions_integration():
    """Lambda role with minimal X-Ray permissions."""
    main_tf = load_text("main.tf")
    assert '"xray:PutTraceSegments"' in main_tf
    assert '"xray:PutTelemetryRecords"' in main_tf


def test_traceability_only_specified_inputs_integration():
    """Only specified inputs: AWS_ENDPOINT, AWS_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY."""
    main_tf = load_text("main.tf")
    variable_names = {
        line.split('"')[1]
        for line in main_tf.splitlines()
        if line.strip().startswith('variable "')
    }
    assert variable_names == {
        "aws_region",
        "aws_endpoint",
        "aws_access_key_id",
        "aws_secret_access_key",
    }


def test_traceability_no_external_variables_or_hard_coded_names_integration():
    """No external variables or hard-coded names."""
    main_tf = load_text("main.tf")
    assert 'variable "name_prefix"' not in main_tf
    assert 'variable "bucket_name"' not in main_tf
    assert 'variable "project_name"' not in main_tf


def test_traceability_deterministic_resource_naming_integration():
    """Deterministic resource naming."""
    resources = state_resources(load_state())
    main_tf = load_text("main.tf")
    assert 'resource "random_id" "bucket_prefix"' in main_tf
    assert 'bucket = "raw-events-${random_id.bucket_prefix.hex}"' in main_tf
    assert resource_values(resources, "aws_s3_bucket.raw_events")["bucket"]


def test_traceability_four_specific_outputs_integration():
    """4 specific outputs (API URL, bucket name, queue URL, RDS endpoint)."""
    outputs = state_outputs(load_state())
    assert set(outputs) == {
        "api_invoke_url",
        "s3_bucket_name",
        "sqs_queue_url",
        "rds_endpoint",
    }
