[pytest]
testpaths = tests
python_files = test_*.py *_tests.py integration_tests.py unit_tests.py
python_classes = Test*
python_functions = test_*
console_output_style = progress
addopts = -v --tb=short
